apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: du4ym3gz3-go
  janus-idp.io/tekton: du4ym3gz3-go
  backstage.io/kubernetes-id: du4ym3gz3-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: du4ym3gz3-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
